// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/pkg/grpc/pb/accounts.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListAdminsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAdminsRequest) Reset()         { *m = ListAdminsRequest{} }
func (m *ListAdminsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAdminsRequest) ProtoMessage()    {}
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{0}
}

func (m *ListAdminsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAdminsRequest.Unmarshal(m, b)
}
func (m *ListAdminsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAdminsRequest.Marshal(b, m, deterministic)
}
func (m *ListAdminsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdminsRequest.Merge(m, src)
}
func (m *ListAdminsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAdminsRequest.Size(m)
}
func (m *ListAdminsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdminsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdminsRequest proto.InternalMessageInfo

type ListAdminsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAdminsReply) Reset()         { *m = ListAdminsReply{} }
func (m *ListAdminsReply) String() string { return proto.CompactTextString(m) }
func (*ListAdminsReply) ProtoMessage()    {}
func (*ListAdminsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{1}
}

func (m *ListAdminsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAdminsReply.Unmarshal(m, b)
}
func (m *ListAdminsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAdminsReply.Marshal(b, m, deterministic)
}
func (m *ListAdminsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdminsReply.Merge(m, src)
}
func (m *ListAdminsReply) XXX_Size() int {
	return xxx_messageInfo_ListAdminsReply.Size(m)
}
func (m *ListAdminsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdminsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdminsReply proto.InternalMessageInfo

type GetAdminRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminRequest) Reset()         { *m = GetAdminRequest{} }
func (m *GetAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdminRequest) ProtoMessage()    {}
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{2}
}

func (m *GetAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminRequest.Unmarshal(m, b)
}
func (m *GetAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminRequest.Marshal(b, m, deterministic)
}
func (m *GetAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminRequest.Merge(m, src)
}
func (m *GetAdminRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdminRequest.Size(m)
}
func (m *GetAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminRequest proto.InternalMessageInfo

type GetAdminReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminReply) Reset()         { *m = GetAdminReply{} }
func (m *GetAdminReply) String() string { return proto.CompactTextString(m) }
func (*GetAdminReply) ProtoMessage()    {}
func (*GetAdminReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{3}
}

func (m *GetAdminReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminReply.Unmarshal(m, b)
}
func (m *GetAdminReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminReply.Marshal(b, m, deterministic)
}
func (m *GetAdminReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminReply.Merge(m, src)
}
func (m *GetAdminReply) XXX_Size() int {
	return xxx_messageInfo_GetAdminReply.Size(m)
}
func (m *GetAdminReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminReply proto.InternalMessageInfo

type GetAdminByEmailRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminByEmailRequest) Reset()         { *m = GetAdminByEmailRequest{} }
func (m *GetAdminByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdminByEmailRequest) ProtoMessage()    {}
func (*GetAdminByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{4}
}

func (m *GetAdminByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminByEmailRequest.Unmarshal(m, b)
}
func (m *GetAdminByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminByEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetAdminByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminByEmailRequest.Merge(m, src)
}
func (m *GetAdminByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetAdminByEmailRequest.Size(m)
}
func (m *GetAdminByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminByEmailRequest proto.InternalMessageInfo

type GetAdminByEmailReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAdminByEmailReply) Reset()         { *m = GetAdminByEmailReply{} }
func (m *GetAdminByEmailReply) String() string { return proto.CompactTextString(m) }
func (*GetAdminByEmailReply) ProtoMessage()    {}
func (*GetAdminByEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{5}
}

func (m *GetAdminByEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAdminByEmailReply.Unmarshal(m, b)
}
func (m *GetAdminByEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAdminByEmailReply.Marshal(b, m, deterministic)
}
func (m *GetAdminByEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdminByEmailReply.Merge(m, src)
}
func (m *GetAdminByEmailReply) XXX_Size() int {
	return xxx_messageInfo_GetAdminByEmailReply.Size(m)
}
func (m *GetAdminByEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdminByEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdminByEmailReply proto.InternalMessageInfo

type CreateAdminRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminRequest) Reset()         { *m = CreateAdminRequest{} }
func (m *CreateAdminRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAdminRequest) ProtoMessage()    {}
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{6}
}

func (m *CreateAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminRequest.Unmarshal(m, b)
}
func (m *CreateAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminRequest.Marshal(b, m, deterministic)
}
func (m *CreateAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminRequest.Merge(m, src)
}
func (m *CreateAdminRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAdminRequest.Size(m)
}
func (m *CreateAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminRequest proto.InternalMessageInfo

type CreateAdminReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAdminReply) Reset()         { *m = CreateAdminReply{} }
func (m *CreateAdminReply) String() string { return proto.CompactTextString(m) }
func (*CreateAdminReply) ProtoMessage()    {}
func (*CreateAdminReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_04e86ddebcfb6d0a, []int{7}
}

func (m *CreateAdminReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAdminReply.Unmarshal(m, b)
}
func (m *CreateAdminReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAdminReply.Marshal(b, m, deterministic)
}
func (m *CreateAdminReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAdminReply.Merge(m, src)
}
func (m *CreateAdminReply) XXX_Size() int {
	return xxx_messageInfo_CreateAdminReply.Size(m)
}
func (m *CreateAdminReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAdminReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAdminReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListAdminsRequest)(nil), "pb.ListAdminsRequest")
	proto.RegisterType((*ListAdminsReply)(nil), "pb.ListAdminsReply")
	proto.RegisterType((*GetAdminRequest)(nil), "pb.GetAdminRequest")
	proto.RegisterType((*GetAdminReply)(nil), "pb.GetAdminReply")
	proto.RegisterType((*GetAdminByEmailRequest)(nil), "pb.GetAdminByEmailRequest")
	proto.RegisterType((*GetAdminByEmailReply)(nil), "pb.GetAdminByEmailReply")
	proto.RegisterType((*CreateAdminRequest)(nil), "pb.CreateAdminRequest")
	proto.RegisterType((*CreateAdminReply)(nil), "pb.CreateAdminReply")
}

func init() {
	proto.RegisterFile("accounts/pkg/grpc/pb/accounts.proto", fileDescriptor_04e86ddebcfb6d0a)
}

var fileDescriptor_04e86ddebcfb6d0a = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd1, 0x83, 0x2c, 0x23, 0xb2, 0x76, 0xb6, 0x96, 0x25, 0xc7, 0xf5, 0xde, 0xc0, 0x7a,
	0x11, 0x3c, 0xad, 0x22, 0x7b, 0xf1, 0xe4, 0x1b, 0x34, 0x35, 0x94, 0x62, 0xda, 0x8e, 0x4d, 0x7a,
	0xc8, 0xcb, 0x8b, 0xa4, 0x36, 0xb4, 0x69, 0xf6, 0xfa, 0xcd, 0x3f, 0xc3, 0xff, 0x31, 0xf0, 0x58,
	0x94, 0x65, 0x37, 0xb4, 0x46, 0x73, 0xfa, 0xae, 0x78, 0xd5, 0x53, 0xc9, 0x49, 0x70, 0x0f, 0x73,
	0xea, 0x3b, 0xd3, 0xe1, 0x35, 0x89, 0xc3, 0x0e, 0x92, 0x8f, 0x5a, 0x9b, 0xd3, 0x57, 0x53, 0xb7,
	0xfa, 0x53, 0xfe, 0x0c, 0x52, 0x9b, 0x43, 0x02, 0xdb, 0x25, 0x24, 0x65, 0x1d, 0x3a, 0xcb, 0x7f,
	0xe2, 0x53, 0x5b, 0xb8, 0x9b, 0x91, 0xcb, 0xec, 0x21, 0xf3, 0xe0, 0xd5, 0xbe, 0x37, 0x45, 0xad,
	0x7c, 0x34, 0x83, 0x34, 0x9a, 0xb8, 0x8d, 0x14, 0xf0, 0xad, 0x97, 0x85, 0x91, 0xc1, 0x61, 0x84,
	0xfb, 0x80, 0x92, 0xb2, 0xc7, 0xdf, 0x2b, 0xd8, 0x9c, 0xa6, 0xfa, 0xf8, 0x0c, 0x30, 0xf7, 0xc3,
	0x87, 0x9c, 0x44, 0x1e, 0x49, 0xb0, 0xdd, 0x1a, 0x93, 0xb2, 0x78, 0x84, 0x8d, 0x2f, 0x82, 0x63,
	0x60, 0x25, 0xc5, 0x92, 0x10, 0xba, 0x9d, 0xf3, 0xac, 0x3e, 0x95, 0x47, 0xb6, 0x4c, 0x85, 0xae,
	0x6c, 0x7f, 0x71, 0xe6, 0x0e, 0xbd, 0xc0, 0xed, 0xc2, 0x0b, 0x33, 0x17, 0x8c, 0xf5, 0x59, 0x1a,
	0x71, 0x52, 0x56, 0xdc, 0x8c, 0x3f, 0x7b, 0xfa, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x22, 0x47, 0x9d,
	0xf6, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsReply, error)
	GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminReply, error)
	GetAdminByEmail(ctx context.Context, in *GetAdminByEmailRequest, opts ...grpc.CallOption) (*GetAdminByEmailReply, error)
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminReply, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsReply, error) {
	out := new(ListAdminsReply)
	err := c.cc.Invoke(ctx, "/pb.Accounts/ListAdmins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*GetAdminReply, error) {
	out := new(GetAdminReply)
	err := c.cc.Invoke(ctx, "/pb.Accounts/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAdminByEmail(ctx context.Context, in *GetAdminByEmailRequest, opts ...grpc.CallOption) (*GetAdminByEmailReply, error) {
	out := new(GetAdminByEmailReply)
	err := c.cc.Invoke(ctx, "/pb.Accounts/GetAdminByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*CreateAdminReply, error) {
	out := new(CreateAdminReply)
	err := c.cc.Invoke(ctx, "/pb.Accounts/CreateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsReply, error)
	GetAdmin(context.Context, *GetAdminRequest) (*GetAdminReply, error)
	GetAdminByEmail(context.Context, *GetAdminByEmailRequest) (*GetAdminByEmailReply, error)
	CreateAdmin(context.Context, *CreateAdminRequest) (*CreateAdminReply, error)
}

// UnimplementedAccountsServer can be embedded to have forward compatible implementations.
type UnimplementedAccountsServer struct {
}

func (*UnimplementedAccountsServer) ListAdmins(ctx context.Context, req *ListAdminsRequest) (*ListAdminsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdmins not implemented")
}
func (*UnimplementedAccountsServer) GetAdmin(ctx context.Context, req *GetAdminRequest) (*GetAdminReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdmin not implemented")
}
func (*UnimplementedAccountsServer) GetAdminByEmail(ctx context.Context, req *GetAdminByEmailRequest) (*GetAdminByEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminByEmail not implemented")
}
func (*UnimplementedAccountsServer) CreateAdmin(ctx context.Context, req *CreateAdminRequest) (*CreateAdminReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdmin not implemented")
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Accounts/ListAdmins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ListAdmins(ctx, req.(*ListAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Accounts/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAdmin(ctx, req.(*GetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAdminByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAdminByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Accounts/GetAdminByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAdminByEmail(ctx, req.(*GetAdminByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Accounts/CreateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAdmins",
			Handler:    _Accounts_ListAdmins_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _Accounts_GetAdmin_Handler,
		},
		{
			MethodName: "GetAdminByEmail",
			Handler:    _Accounts_GetAdminByEmail_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _Accounts_CreateAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/pkg/grpc/pb/accounts.proto",
}
